name: Keep Alive

on:
  schedule:
    # Run every 5 minutes
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  ping-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ping Server
        run: |
          echo "Keep-alive workflow placeholder. Custom pipeline steps can be added here."
